//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IMyService")]
    public interface IMyService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyService/SendMessage", ReplyAction = "http://tempuri.org/IMyService/SendMessageResponse")]
        string SendMessage(string from, string to);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMyService/SendEmplMessage", ReplyAction = "http://tempuri.org/IMyService/SendEmplMessageResponse")]
        string SendEmplMessage(string from, string message, string to);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService
    {

        public MyServiceClient()
        {
        }

        public MyServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public MyServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string SendMessage(string from, string to)
        {
            return base.Channel.SendMessage(from, to);
        }

        public string SendEmplMessage(string from, string message, string to)
        {
            return base.Channel.SendEmplMessage(from, message, to);
        }
    }
}
